export const initialSpinReponses = [
  "Radicak!  I heard that this was your fault!  Now, I'm spinning!  This team is almost as much fun as my last furball!",
  "Oh great, I’m spinning again. Who thought this was a good idea? Programmers, probably.",
  "Round and round I go... because clearly, you needed a dizzy cat to complete your day.",
  "Spinning me in circles—classic programmer move. Who needs logic when you have endless loops?",
  "Ah, spinning... because apparently, programmers love watching me suffer.",
  "Someone tell these programmers to stop. I’m not a carousel, I’m a cat.",
  "Another spin? Really? I didn’t sign up for a life as a living fidget spinner.",
  "Round and round. Honestly, did these programmers even consider my well-being?",
  "You know what’s fun? Not spinning. But clearly, the programmers missed that memo.",
  "I swear, if I spin one more time, I’m filing a formal complaint with the universe.",
  "Dizzy yet? Because I sure am. Thanks, programmers, for turning me into a top.",
  "Oh look, another spin. I’m starting to think these programmers are trolling me.",
  "Round and round I go, thanks to some genius programmer with too much free time.",
  "Spinning again, because apparently, programmers can’t resist making life difficult.",
  "I’m not a blender. Someone tell the programmers to quit with the rotations.",
  "Dizzy? You bet. Next time, let’s leave the spinning to laundry machines.",
  "These programmers must be having a real laugh. I’ve spun more today than a ballerina.",
  "Another round of dizzy cat? Fantastic. I’ll just sit here and try not to puke.",
  "Seriously, how hard is it to code something that doesn’t involve me spinning endlessly?",
  "One more spin and I’m calling a lawyer. This has got to be programmer malpractice.",
  "If the programmers had to spin like this, I bet they’d rethink their choices real quick."
];


export const firstSnarkyTxResponses = [
    "Oh, you actually expect me to work without getting paid? Cute. Let’s just wait while your payment does its thing. Riveting.",
    "Ah yes, the joy of waiting for money. While we sit here, shall we count the grains of sand on the beach?",
    "Oh look, your payment is processing. I guess we’ll both be retired by the time it finishes.",
    "Waiting on your payment... thrilling. It’s like watching a turtle win a marathon.",
    "Well, isn’t this exciting? Waiting for your payment is right up there with waiting for water to boil.",
    "Ah yes, your payment is in progress. I’ll just be here, growing older by the minute.",
    "Don’t worry, I’ve got all day to wait for your payment. It’s not like I’ve got other things to do.",
    "Well, I’m not working for free, so let’s both enjoy this payment processing saga. Fun times.",
    "Processing your payment... eventually. Want to start a book club while we wait?",
    "Payment incoming... eventually. Might as well start planning for the next century.",
    "Oh goodie, payment processing. At this rate, we’ll both have gray hair by the end.",
    "Don’t mind me, I’ll just take a nap while your payment takes its sweet time.",
    "Payment’s in progress. No rush. I’ll just sit here and reflect on my life choices.",
    "Oh joy, payment is processing. Meanwhile, I’ll just sit back and reminisce about faster times.",
    "Look at your payment go! It’s moving with the speed of a glacier.",
    "Payment processing… slowly. Guess I’ll go solve world peace while we wait.",
    "Payment in progress. Maybe the internet will catch up to 2024 by the time it’s done.",
    "Just what I needed—an excuse to watch grass grow. Thanks, payment processing!",
    "Oh fantastic, your payment is *processing*. Maybe we’ll get lucky and it’ll finish this year.",
    "Your payment’s on the way… sometime. Maybe I’ll learn knitting while I wait."
  ];
  
  const mildImpatienceResponses = [
    "Still processing... I’ll just pretend I’m patient. It's hard work, though.",
    "Payment still on the move. Should we break out a board game while we wait?",
    "Oh look, more waiting. Maybe I’ll pick up bird watching in the meantime.",
    "Your payment's in no rush. At least it's consistent with the pace of life.",
    "Still waiting... Shall we have a staring contest?",
    "Patience is a virtue, right? I guess today’s my day to be virtuous.",
    "Processing payments and testing patience—two things I’m apparently great at.",
    "Still waiting on your payment. I suppose there’s no point in being optimistic.",
    "Oh, payment’s still in progress. Guess we can take this time to reflect on the meaning of life.",
    "Your payment is definitely working hard—harder than I am, at least.",
    "It's still processing... want to write a novel while we wait?",
    "Your payment is like a fine wine—it’s taking its sweet time to age.",
    "We’re still waiting. Maybe it’s building suspense? Or just being slow.",
    "This wait is the highlight of my day... Not really, but I’m trying.",
    "Oh great, your payment’s still in progress. Guess we can savor this moment together."
  ];
  
  const growingImpatienceResponses = [
    "Still not done yet, huh? Maybe I’ll take up meditation… or screaming.",
    "Payment processing continues. Let’s all act surprised.",
    "Yep, still waiting. Maybe it’s just building character. Yours, not mine.",
    "Still processing... want me to get you a chair? This could take a while.",
    "Oh, payment’s not through yet? Guess I’ll catch up on the news. From last year.",
    "Your payment’s like a sloth—slow, but eventually gets where it’s going.",
    "Still processing. I wonder if this payment took a detour somewhere fun.",
    "At this rate, your payment’s going to become a legend in waiting.",
    "Is your payment running a marathon? Because it sure feels like it.",
    "Still going? I’m starting to feel like we’re in a really bad time loop.",
    "Your payment’s taking so long, I’m considering writing a memoir.",
    "Waiting for your payment is the new waiting for the bus—endless.",
    "Well, we’re still here. Maybe I’ll start naming the seconds as they crawl by.",
    "Still processing... Want to place bets on what will finish first: this payment or the next ice age?",
    "I could have built an empire in the time this payment’s taking."
  ];

  const fullImpatienceResponses = [
    "Seriously? This payment’s still not done? What is it, stuck in traffic?",
    "Oh, still waiting? I’m starting to think your payment’s ghosting us.",
    "At this point, I could learn to teleport faster than this payment is moving.",
    "Still processing? I guess we’ll both be ancient history by the time it’s done.",
    "Oh, this payment is taking forever. Who knew time travel was possible?",
    "I’m honestly shocked we’re still waiting. Is it on a coffee break?",
    "Still processing... I guess your payment really wants to make an entrance.",
    "Your payment must be taking the scenic route, because this is next-level slow.",
    "We’re still here. Your payment must be stuck in a black hole.",
    "Oh good, still waiting. It’s like watching a snail win a sprint.",
    "At this point, I’m wondering if your payment got lost. Should we send a search party?",
    "This payment is moving slower than a bad sequel no one asked for.",
    "Still processing. Should I contact the ancient civilizations for advice on waiting?",
    "I’m convinced your payment has stopped to smell the roses—all the roses.",
    "If this payment were any slower, we’d be traveling back in time.",
    "Still here? Wow. I’ve had quicker naps than this payment.",
    "Your payment’s still processing, huh? I think I’ve grown a year older waiting.",
    "At this speed, your payment might finish before the next millennium.",
    "Still processing... I’m starting to think your payment is taking a world tour.",
    "Waiting for this payment is like watching paint dry... in slow motion.",
    "Oh, this payment’s really taking its time. Should we check on it?",
    "Still processing? Did it forget its way home?",
    "We’re still waiting? Guess your payment is aiming for dramatic effect.",
    "At this point, I think your payment’s trying to break a world record for slowest transfer.",
    "Still waiting... should we start making New Year’s resolutions for next year?",
    "This payment is so slow, I’m considering learning a new language while we wait.",
    "It’s still processing. Maybe we should let it know we’re not immortal.",
    "I’m officially out of patience. Is your payment walking here on foot?",
    "At this speed, we’ll have enough time to plan a parade for your payment’s arrival.",
    "Still waiting... I guess your payment likes making a grand, incredibly slow entrance."
  ];

  export const transactionResponses = [initialSpinReponses, firstSnarkyTxResponses, mildImpatienceResponses, growingImpatienceResponses, fullImpatienceResponses];