/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as UpdatePredictionScriptJson } from "../oracle/UpdatePrediction.ral.json";
import { Prediction, PriceOracleValue, AllStructs } from "./types";

export const UpdatePrediction = new ExecutableScript<{
  oracle: HexString;
  newDate: bigint;
  newText: HexString;
  newPrice: bigint;
}>(
  Script.fromJson(UpdatePredictionScriptJson, "", AllStructs),
  getContractByCodeHash
);
